name: btd_test
hyperparameters:
  global_batch_size: 8
  data_location: /mnt/nfs_worker/btd_data
  arch: cnn
  workers: 4
  lr: 0.1
  momentum: 0.9
  weight_decay: 1e-4
  evaluate: store_true
  pretrained: True
  dataset: BTDTrial
records_per_epoch: 50000
searcher:
  name: single
  metric: val_loss
  smaller_is_better: true
  max_length:
    epochs: 60
entrypoint: model_def:BTDTrial
# set to imagenet path
bind_mounts:
  - host_path: /mnt/nfs_worker
    container_path: /mnt/nfs_worker
profiling:
  begin_on_batch: 0
  enabled: true
  end_after_batch: null
resources:
    slots_per_trial: 2

